

INSERT INTO QuestionPool (ID, correctAnswer, Question)
VALUES
(1, 'B', 'Which of the following is a valid Python data type?\nA. folder\nB. list\nC. script\nD. node'),
(2, 'True', 'Python is a dynamically typed language. (True/False)'),
(3, 'False', 'Python uses curly braces to define code blocks. (True/False)'),
(4, 'Indentation', 'What is used to define blocks of code in Python?'),
(5, 'C', 'Which operator is used for exponentiation in Python?\nA. ^\nB. exp\nC. **\nD. power'),
(6, 'True', 'ASP.NET supports both MVC and Web API. (True/False)'),
(7, 'A', 'Which of these is a valid HTTP method?\nA. POST\nB. PUSH\nC. FETCH\nD. LOAD'),
(8, 'C#', 'What language is commonly used with ASP.NET Core?'),
(9, 'Model-View-Controller', 'What does MVC stand for?'),
(10, 'False', 'ASP.NET cannot be used for RESTful services. (True/False)'),
(11, 'Structured Query Language', 'What does SQL stand for?'),
(12, 'A', 'Which SQL statement is used to remove a table?\nA. DROP\nB. REMOVE\nC. DELETE\nD. CLEAR'),
(13, 'B', 'Which keyword is used to return only unique values?\nA. UNIQUE\nB. DISTINCT\nC. SELECT\nD. FILTER'),
(14, 'JOIN', 'What keyword is used to combine rows from two or more tables?'),
(15, 'False', 'You must use WHERE in every SQL SELECT query. (True/False)'),
(16, 'A', 'Which language is commonly used with Flutter?\nA. Dart\nB. Kotlin\nC. Swift\nD. C#'),
(17, 'True', 'React Native allows development for both iOS and Android. (True/False)'),
(18, 'Android Studio', 'Which IDE is typically used for Android development?'),
(19, 'B', 'Which OS is Swift used for?\nA. Android\nB. iOS\nC. Windows\nD. Linux'),
(20, 'False', 'Mobile apps cannot access device hardware. (True/False)'),
(21, 'C', 'Which data structure uses LIFO?\nA. Queue\nB. Tree\nC. Stack\nD. Graph'),
(22, 'True', 'A queue is FIFO (First In, First Out). (True/False)'),
(23, 'Binary Search', 'Which algorithm is best for searching in a sorted array?'),
(24, 'False', 'A linked list allows random access. (True/False)'),
(25, 'D', 'Which is NOT a type of tree?\nA. AVL\nB. Binary\nC. B-Tree\nD. Circle'),
(26, 'True', 'Firewalls prevent unauthorized access to networks. (True/False)'),
(27, 'B', 'What does HTTPS stand for?\nA. Hypertext Transfer Push Security\nB. Hypertext Transfer Protocol Secure\nC. HTTP Secureline\nD. Host Transfer Secure'),
(28, 'Encryption', 'What is the process of converting data into a secret code called?'),
(29, 'False', 'Passwords should be stored in plain text. (True/False)'),
(30, 'A', 'Which of the following is a common cyber attack?\nA. Phishing\nB. Fishing\nC. Surfing\nD. Tracking'),
(31, 'C', 'Which of these is a Python library for ML?\nA. React\nB. Flask\nC. Scikit-learn\nD. Redux'),
(32, 'True', 'Supervised learning requires labeled data. (True/False)'),
(33, 'Classification', 'What is the process of categorizing data into classes called?'),
(34, 'False', 'AI and ML are exactly the same thing. (True/False)'),
(35, 'Overfitting', 'What do we call a model that performs well on training data but poorly on unseen data?'),
(36, 'B', 'Which language is used to style HTML?\nA. HTML\nB. CSS\nC. PHP\nD. JS'),
(37, 'True', 'HTML is used for structuring web pages. (True/False)'),
(38, 'DOM', 'What does the browser create from HTML that JavaScript can interact with?'),
(39, 'A', 'Which tag is used to link a CSS file?\nA. <link>\nB. <style>\nC. <script>\nD. <css>'),
(40, 'False', 'You cannot use JavaScript in HTML. (True/False)'),
(41, 'True', 'CI/CD pipelines are part of DevOps. (True/False)'),
(42, 'Docker', 'Which tool is used to containerize applications?'),
(43, 'C', 'Which is a cloud provider?\nA. Oracle\nB. Cisco\nC. AWS\nD. MySQL'),
(44, 'Infrastructure as Code', 'What does IaC stand for?'),
(45, 'False', 'DevOps is only about writing code. (True/False)'),
(46, 'D', 'Which software model handles risk best?\nA. Agile\nB. Waterfall\nC. Incremental\nD. Spiral'),
(47, 'Requirement Gathering', 'What is the first phase in the software life cycle?'),
(48, 'True', 'TCP ensures reliable data transmission. (True/False)'),
(49, 'C', 'What does IP stand for?\nA. Internal Process\nB. Internet Packet\nC. Internet Protocol\nD. Inter-Process'),
(50, 'OSI Model', 'What model divides network communication into 7 layers?');
go
