INSERT INTO Person.[usertable] ([name], [password], [role], [email])
VALUES
(N'ahmed hassan',      N'ahmed123',   N'Student',      N'ahmed.hassan@example.com'),
(N'sara mahmoud',      N'sara456',    N'Student',      N'sara.mahmoud@example.com'),
(N'mohamed ali',       N'mohamed789', N'Instructor',   N'mohamed.ali@example.com'),
(N'menna fathy',       N'menna321',   N'Training Manager', N'menna.fathy@example.com'),
(N'ibrahim adel',      N'ibrahim654', N'Student',      N'ibrahim.adel@example.com'),
(N'dina elmasry',      N'dina987',    N'Instructor',   N'dina.elmasry@example.com'),
(N'tarek nabil',       N'tarek111',   N'Student',      N'tarek.nabil@example.com'),
(N'nourhan youssef',   N'nourhan222', N'Training Manager', N'nourhan.youssef@example.com'),
(N'youssef mostafa',   N'youssef333', N'Instructor',   N'youssef.mostafa@example.com'),
(N'reem kamal',        N'reem444',    N'Student',      N'reem.kamal@example.com'),

(N'hossam gabr',       N'hossam555',  N'Student',      N'hossam.gabr@example.com'),
(N'layla adel',        N'layla666',   N'Instructor',   N'layla.adel@example.com'),
(N'karim lotfy',       N'karim777',   N'Training Manager', N'karim.lotfy@example.com'),
(N'fatma naguib',      N'fatma888',   N'Student',      N'fatma.naguib@example.com'),
(N'walid tarek',       N'walid999',   N'Instructor',   N'walid.tarek@example.com'),
(N'rania helmy',       N'rania000',   N'Training Manager', N'rania.helmy@example.com'),
(N'alaa yassin',       N'alaa101',    N'Student',      N'alaa.yassin@example.com'),
(N'noha sami',         N'noha202',    N'Instructor',   N'noha.sami@example.com'),
(N'mostafa shawky',    N'mostafa303', N'Student',      N'mostafa.shawky@example.com'),
(N'esraa nader',       N'esraa404',   N'Training Manager', N'esraa.nader@example.com'),

(N'adel badr',         N'adel505',    N'Student',      N'adel.badr@example.com'),
(N'mai fouad',         N'mai606',     N'Instructor',   N'mai.fouad@example.com'),
(N'hany zaki',         N'hany707',    N'Training Manager', N'hany.zaki@example.com'),
(N'yara magdy',        N'yara808',    N'Student',      N'yara.magdy@example.com'),
(N'omar fekry',        N'omar909',    N'Instructor',   N'omar.fekry@example.com'),
(N'nahla said',        N'nahla010',   N'Training Manager', N'nahla.said@example.com'),
(N'khaled mansour',    N'khaled121',  N'Student',      N'khaled.mansour@example.com'),
(N'mirna saber',       N'mirna232',   N'Instructor',   N'mirna.saber@example.com'),
(N'shady roshdy',      N'shady343',   N'Student',      N'shady.roshdy@example.com'),
(N'heba rami',         N'heba454',    N'Training Manager', N'heba.rami@example.com'),

(N'tamer fathi',       N'tamer565',   N'Student',      N'tamer.fathi@example.com'),
(N'nadine ayman',      N'nadine676',  N'Instructor',   N'nadine.ayman@example.com'),
(N'ziad ashraf',       N'ziad787',    N'Training Manager', N'ziad.ashraf@example.com'),
(N'mariam anwar',      N'mariam898',  N'Student',      N'mariam.anwar@example.com'),
(N'fady kamel',        N'fady909',    N'Instructor',   N'fady.kamel@example.com'),
(N'yasmine adel',      N'yasmine010', N'Training Manager', N'yasmine.adel@example.com'),
(N'ayman galal',       N'ayman121',   N'Student',      N'ayman.galal@example.com'),
(N'nesma khalil',      N'nesma232',   N'Instructor',   N'nesma.khalil@example.com'),
(N'samir zohdy',       N'samir343',   N'Student',      N'samir.zohdy@example.com'),
(N'malak tamer',       N'malak454',   N'Training Manager', N'malak.tamer@example.com'),

(N'ramy ehab',         N'ramy565',    N'Student',      N'ramy.ehab@example.com'),
(N'hagar osama',       N'hagar676',   N'Instructor',   N'hagar.osama@example.com'),
(N'thabet yehia',      N'thabet787',  N'Training Manager', N'thabet.yehia@example.com'),
(N'dalia elhady',      N'dalia898',   N'Student',      N'dalia.elhady@example.com'),
(N'bassel nashaat',    N'bassel909',  N'Instructor',   N'bassel.nashaat@example.com'),
(N'rana abdallah',     N'rana010',    N'Training Manager', N'rana.abdallah@example.com'),
(N'salim gawish',      N'salim121',   N'Student',      N'salim.gawish@example.com'),
(N'huda refaat',       N'huda232',    N'Instructor',   N'huda.refaat@example.com'),
(N'mahmoud ghoneim',   N'mahmoud343', N'Student',      N'mahmoud.ghoneim@example.com'),
(N'lamia reda',        N'lamia454',   N'Training Manager', N'lamia.reda@example.com'); -- ✅ no comma here
